#============================================================================
# Title       : Makefile
# Description : Makefile for qdda (quick & dirty dedupe analyzer)
# Author      : Bart Sjerps <bart@outrun.nl>
# License     : GPLv3+
# ---------------------------------------------------------------------------

prefix = /usr/local

DATE     = `date +'%Y%m%d%H%M'`

# not used - may be used to generate build numbers as hours since 1-1-2010
EPOCH    = `date -u +'%s'`
ESTART   = `date -u --date="Jan 1 00:00:00 2010" +'%s'`
BUILD    = $$(( ($(EPOCH) - $(ESTART)) / 60 ))

VERSION ?= 0.1
CFLAGS  += -Wall
CFLAGS  += -std=c++0x
CFLAGS  += -O
LIBS     = -lsqlite3 -lstdc++ -lz
STATIC   = /usr/lib64/liblz4.a

all: qdda

# Static linking of lz4 avoids having to install dependencies
# The other libs are usually available on most Linux systems
# Note that building on newer systems causes problems with
# older versions of LIBC and STDC++ libraries
# LZ4 needs to be version 1.31 (or higher).

qdda: qdda.o
	g++ $(LDFLAGS) qdda.o $(LIBS) $(STATIC) -o qdda 

qdda.o: qdda.cpp version.h
	g++ -c $(CFLAGS) qdda.cpp

# This sets correct version when building RPM
# Defaults to version 0.1 if not specified
version.h:
	@echo "// generated by makefile"             > version.h
	@echo "#define progversion	\"$(VERSION)\"" >> version.h
	@echo "#define builddate	\"$(DATE)\""    >> version.h

clean:
	rm -rf *.o qdda version.h

install: qdda
	install -d 0755 $(prefix)/bin
	install -m 0755 qdda $(prefix)/bin

.PHONY: install

